/**
 * 内置帮助文档（M·485）：`帮助` 命令在用户笔记本创建/复用「小驴闪卡/使用帮助」文档并打开。
 * 双语按内核语言选择；内容与 docs/21 上手指南保持同源精简。
 */

const HELP_ZH = `# 小驴闪卡 · 使用帮助

> 本文档由插件生成，可搜索、可编辑；更新插件后可在命令面板重新打开最新版。

## 快速上手

1. **制卡**：选中任意块 → 点击块左侧图标 → 「添加到卡组」；或选中文本 → 「挖空并制卡」。
2. **复习**：顶栏驴头角标点击直达；或命令面板「开始复习」。空格翻面，1-4 评分（三档模式 1-3）。
3. **统计**：命令面板「打开闪卡中心」→ 总览页看热力图、保持率与里程碑。

## 常用快捷键（复习面板内）

| 键 | 作用 |
|---|---|
| 空格 / Enter | 显示答案 / 评良好 |
| 1-4 | 评分（遗忘/困难/良好/简单） |
| x 或 0 | 跳过本张 |
| p / q | 撤销上一评 |
| f | 快速改期（N 天后到期） |
| s | 今天不学此卡 |
| [ | 回看上一张 |
| ? | 快捷键速查浮层 |

## 制卡方式一览

- **块制卡**：块图标菜单 → 添加到卡组（支持多选批量）
- **挖空制卡**：编辑器选中文本 → 菜单「挖空并制卡」（包 ==高亮==）
- **快速问答**：命令面板「快速制卡」
- **标记符制卡**：文档里写 \`术语:: 定义\` 或以「？」结尾的段落 → 命令「扫描本文档标记符制卡」
- **AI 批量制卡**：设置配置 AI → 闪卡中心 → AI 向导（支持当前文档/笔记本/选区/粘贴）
- **图片遮挡**：块图标菜单 → 制作遮挡卡，在图上画框即卡

## 复习技巧

- **忘记卡本批重现**：评「遗忘」的卡会在本批末尾再出现一次（仅本地强化，不影响内核调度），可在设置关闭
- **范围选择**：复习页左上角可切 全部/仅新卡/仅旧卡/按卡组/按笔记本
- **睡前巩固**：命令面板「睡前巩固（只学新卡）」
- **限时挑战 / 配对挑战**：命令面板直达，纯练习不计调度

## 数据与隐私

- 复习日志、考试计划等全部存储在本地工作区（设置→数据 可导出/导入/清空）
- 评分永远调用思源内核 FSRS 调度，插件只做增值层；卸载插件不影响已有卡片
- AI 制卡仅在配置后调用你指定的服务，键值保存在本工作区 settings.json

### 复习日志统计口径

- **时间**：全部按设备本地时区记录，「学习日」为本地零点分界
- **明细上限**：本地明细保留最近 2 万条评分；更早日子的每日聚合（热力图/连击）作为快照保留，不因截断回退
- **作答耗时**：仅插件复习面板记录（题面呈现到评分），超过「单卡作答计时上限」按上限计；原生复习界面的评分没有耗时字段，统计留空而不是补 0
- **覆盖率**：总览的「卡片覆盖」= 本地有评分记录的卡 ÷ 内核卡组规模合计；覆盖率≠掌握率
- **CSV 导出**：「duration」列为作答耗时秒（空=缺失）；「review_state」列本地恒为空（内核复习状态未开放给插件，不猜测）

## 遇到问题

- 设置 → 数据 → 「复制诊断」生成版本与环境信息
- 更多文档见 GitHub 仓库 docs/ 目录
`;

const HELP_EN = `# Lv Cards · Help

> Generated by the plugin. Reopen from the command palette to refresh after updates.

## Quick start

1. **Make a card**: select a block -> block icon -> "Add to deck"; or select text -> "Cloze & make card".
2. **Review**: click the donkey badge in the top bar, or run "Start review" from the command palette. Space flips, keys 1-4 rate.
3. **Stats**: "Open hub" -> Overview tab for heatmap, retention and milestones.

## Shortcuts (inside review)

| Key | Action |
|---|---|
| Space / Enter | Show answer / rate Good |
| 1-4 | Rate (Again/Hard/Good/Easy) |
| x or 0 | Skip |
| p / q | Undo last rating |
| f | Quick reschedule (N days) |
| s | Skip this card today |
| [ | Peek previous card |
| ? | Shortcut cheat sheet |

## Ways to create cards

- **Block card**: block icon menu -> Add to deck (multi-select supported)
- **Cloze**: select text in the editor -> "Cloze & make card" (wraps in ==mark==)
- **Quick Q/A**: command palette -> "Quick card"
- **Markers**: write \`term:: definition\` or end a paragraph with ? -> run the scan command
- **AI batch**: configure AI in settings -> AI wizard (current doc / notebook / selection / paste)
- **Image occlusion**: block icon menu -> Create occlusion

## Review tips

- Cards rated **Again** re-appear once at the end of the batch (local reinforcement only; scheduling untouched)
- **Scope picker** (top-left of review): all / new only / old only / per deck / per notebook
- **Evening cram**: command palette entry for new-cards-only sessions
- **Timed challenge / Pairing**: command palette, pure practice — no scheduling

## Data & privacy

- Review log, exam plans etc. live in your workspace (Settings -> Data to export/import/clear)
- Scheduling always goes through the SiYuan kernel FSRS; the plugin is an add-on layer only
- AI card generation calls only the endpoint you configure; keys are stored in this workspace

### Review log statistics conventions

- **Time**: recorded in the device's local timezone; a "study day" ends at local midnight
- **Detail cap**: the last 20,000 ratings are kept as details; older daily aggregates (heatmap/streak) are preserved as snapshots and never regress
- **Answer time**: only recorded by the plugin review panel (card shown -> rating), capped by the "per-card time cap"; native UI ratings have no duration field and stay empty instead of 0
- **Coverage**: overview "card coverage" = cards with local ratings ÷ total kernel deck sizes; coverage ≠ mastery
- **CSV export**: the "duration" column is answer seconds (empty = missing); "review_state" is always empty locally (kernel review state is not exposed; never guessed)

## Troubleshooting

- Settings -> Data -> "Copy diagnostics" for version/environment info
- See the docs/ folder in the GitHub repository
`;

export function helpMarkdown(lang: string): string {
    return lang && !lang.startsWith("zh") ? HELP_EN : HELP_ZH;
}

/** 示例工作区（476）的 5 张示例卡内容：与帮助文案同 chunk，不占主包预算 */
export function sampleCards(): string[] {
    return [
        "示例 1 · 普通卡：思源内核的 FSRS 调度负责计算间隔，小驴闪卡负责体验增强。",
        "示例 2 · 公式卡：质能方程 $E = mc^2$ 中 $c$ 代表什么？\n光速（约 3×10⁸ m/s）。",
        "示例 3 · 挖空卡：FSRS 的四个核心状态是 ==未学习、学习、复习、悬置==。",
        "示例 4 · 列表卡：FSRS 评分四档\n* 遗忘（Again）\n* 困难（Hard）\n* 良好（Good）\n* 简单（Easy）",
        "示例 5 · 问答卡：什么是真实保持率（True Retention）？\n按卡片成熟度分层统计的记忆保持比例，比整体正确率更能反映记忆效果。",
    ];
}
